image: maven:3.3.9-jdk-8

stages:
 - validate
 - test
 - build
 - artifact
 - deploy

validate:
  stage: validate
  script:
    - mvn validate

test:
    stage: test
    script:
      -   mvn test

build:
  stage: build
  script:
    - mvn package

