image: maven:3.3.9-jdk-8

stages:
 - validate
 - test
 - build
 - deploy

validate:
  stage: validate
  script:
    - mvn validate

test:
    stage: test
    script:
      -   mvn test

build:
  stage: build
  script:
    - mvn package

deploy:
      stage: deploy
      script:
        - git remote add heroku https://fabiofont.alexandre:$heroku@git.heroku.com/demoautomationtest.git
        - git push heroku master
      environment:
        name: producao
        url: https://demoautomationtest.herokuapp.com/
      only:
        - master
      when: manual


